import { CAPABILITIES } from '../capabilities.js';
import type { NormalizedPolicyInput } from '../types.js';
import { actionTarget, proxyName, referencedPoolIds, yamlString } from './shared.js';

const matchNames = {
  DOMAIN: 'DOMAIN',
  DOMAIN_SUFFIX: 'DOMAIN-SUFFIX',
  DOMAIN_KEYWORD: 'DOMAIN-KEYWORD',
  DOMAIN_REGEX: 'DOMAIN-REGEX',
  IP_CIDR: 'IP-CIDR',
  IP_CIDR6: 'IP-CIDR6',
  GEOIP: 'GEOIP',
  GEOSITE: 'GEOSITE',
  DST_PORT: 'DST-PORT',
  NETWORK: 'NETWORK',
} as const;

export function compileMihomo(input: NormalizedPolicyInput): string {
  const lines = ['# Generated by ProxyHub. First Match Wins.', 'proxies:'];
  for (const node of input.nodes) {
    lines.push(
      `  - name: ${yamlString(proxyName(node.name, node.id))}`,
      '    type: vless',
      `    server: ${yamlString(node.host)}`,
      `    port: ${String(node.port)}`,
      `    uuid: ${yamlString(node.uuid)}`,
      `    flow: ${yamlString(node.flow)}`,
      '    encryption: ""',
      '    udp: true',
      '    network: tcp',
      '    tls: true',
      `    servername: ${yamlString(node.sni)}`,
      `    client-fingerprint: ${yamlString(node.fingerprint)}`,
      '    reality-opts:',
      `      public-key: ${yamlString(node.realityPublicKey)}`,
      `      short-id: ${yamlString(node.shortId)}`,
    );
  }
  lines.push('proxy-groups:');
  const usedPools = referencedPoolIds(input);
  for (const pool of input.nodePools.filter((item) => usedPools.has(item.id))) {
    const members = pool.members
      .map((member) => input.nodeById.get(member.nodeId))
      .filter((node) => node !== undefined);
    const type =
      pool.strategy === 'FALLBACK'
        ? 'fallback'
        : pool.strategy === 'AUTO' || pool.strategy === 'LATENCY_BASED'
          ? 'url-test'
          : pool.strategy === 'LOAD_BALANCE'
            ? 'load-balance'
            : 'select';
    lines.push(`  - name: ${yamlString(pool.name)}`, `    type: ${type}`);
    if (members.length) {
      lines.push('    proxies:');
      for (const node of members)
        lines.push(`      - ${yamlString(proxyName(node.name, node.id))}`);
    } else lines.push('    proxies: []');
    if (type === 'fallback' || type === 'url-test') {
      lines.push('    url: "https://www.gstatic.com/generate_204"', '    interval: 300');
    }
  }
  lines.push('rules:');
  for (const rule of input.rules) {
    if (!CAPABILITIES.mihomo.ruleTypes.has(rule.matchType)) continue;
    const target = actionTarget(input, rule.actionType, rule.nodePoolId);
    lines.push(`  - ${yamlString(`${matchNames[rule.matchType]},${rule.matchValue},${target}`)}`);
  }
  lines.push(
    `  - ${yamlString(`MATCH,${actionTarget(input, input.policy.defaultAction, input.policy.defaultNodePoolId)}`)}`,
  );
  return `${lines.join('\n')}\n`;
}
