// @ts-nocheck -- This bootstrap runs before TypeScript packages exist; behavior is regression-tested.
import { readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const sourcePath = resolve(root, 'release/version.json');
const targetPath = resolve(root, 'packages/shared/src/generated/release-version.ts');
const source = JSON.parse(await readFile(sourcePath, 'utf8'));

if (
  typeof source.version !== 'string' ||
  !/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(source.version) ||
  typeof source.xrayVersion !== 'string' ||
  !/^\d+\.\d+\.\d+$/.test(source.xrayVersion) ||
  !Number.isSafeInteger(source.manifestSchemaVersion) ||
  source.manifestSchemaVersion < 1
) {
  throw new Error('release/version.json is invalid');
}

const quote = (value) => `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`;
const generated = `// Generated by scripts/release/generate-version.mjs. Do not edit manually.
export const PROXYHUB_RELEASE = {
  version: ${quote(source.version)},
  xrayVersion: ${quote(source.xrayVersion)},
  manifestSchemaVersion: ${source.manifestSchemaVersion},
} as const;
`;

if (process.argv.includes('--check')) {
  const current = await readFile(targetPath, 'utf8').catch(() => '');
  if (current !== generated) {
    throw new Error('Generated release version is stale; run pnpm release:generate-version');
  }
} else {
  await writeFile(targetPath, generated, { encoding: 'utf8', mode: 0o644 });
}
